import { pick, buildOptions } from "./rng.mjs";

// Curated General Awareness facts (static GK relevant to SSC CGL).
// Each: [question, answer, [distractors], explanation]. Significantly expanded.
const POOLS = {
  "Indian Polity": [
    ["Who is the head of the State in India?", "President", ["Prime Minister", "Chief Justice", "Vice President"], "The President is the constitutional head of the Indian State."],
    ["How many fundamental rights are guaranteed by the Indian Constitution?", "6", ["7", "5", "8"], "There are 6 Fundamental Rights after the Right to Property was removed."],
    ["Which Article deals with the Right to Constitutional Remedies?", "Article 32", ["Article 19", "Article 21", "Article 14"], "Article 32 is called the 'heart and soul' of the Constitution by Dr. Ambedkar."],
    ["The Rajya Sabha is also known as the?", "Council of States", ["House of the People", "Lower House", "Lok Sabha"], "Rajya Sabha is the Council of States (Upper House)."],
    ["Who appoints the Chief Justice of India?", "President", ["Prime Minister", "Parliament", "Law Minister"], "The President appoints the CJI."],
    ["The Directive Principles of State Policy are borrowed from which country?", "Ireland", ["USA", "UK", "Canada"], "DPSP are inspired by the Constitution of Ireland."],
    ["Who is the Supreme Commander of the Indian Armed Forces?", "President", ["Prime Minister", "Defence Minister", "Army Chief"], "The President is the Supreme Commander of the Armed Forces."],
    ["The concept of 'Fundamental Duties' was added by which amendment?", "42nd Amendment", ["44th Amendment", "1st Amendment", "73rd Amendment"], "The 42nd Amendment (1976) added Fundamental Duties (Article 51A)."],
    ["How many schedules are there in the Indian Constitution?", "12", ["10", "8", "11"], "The Constitution currently has 12 Schedules."],
    ["Who has the power to declare a financial emergency?", "President", ["Finance Minister", "RBI Governor", "Parliament"], "Under Article 360, the President can declare a financial emergency."],
    ["The minimum age to become the President of India is?", "35 years", ["25 years", "30 years", "40 years"], "A person must be at least 35 years old to be President."],
    ["The Preamble to the Constitution was amended only once by which amendment?", "42nd Amendment", ["44th Amendment", "1st Amendment", "24th Amendment"], "The 42nd Amendment (1976) added 'Socialist', 'Secular' and 'Integrity'."],
    ["Who is known as the guardian of the public purse in India?", "Comptroller and Auditor General", ["Finance Minister", "RBI Governor", "President"], "The CAG audits government accounts and is the guardian of the public purse."],
    ["Which house is called the permanent house of Parliament?", "Rajya Sabha", ["Lok Sabha", "Vidhan Sabha", "Vidhan Parishad"], "Rajya Sabha is permanent; one-third of members retire every two years."],
  ],
  "History": [
    ["Who was the first Governor-General of independent India?", "Lord Mountbatten", ["C. Rajagopalachari", "Lord Canning", "Warren Hastings"], "Lord Mountbatten was the first Governor-General of independent India (1947)."],
    ["The Quit India Movement was launched in which year?", "1942", ["1930", "1920", "1947"], "The Quit India Movement began on 8 August 1942."],
    ["Who founded the Maurya Empire?", "Chandragupta Maurya", ["Ashoka", "Bindusara", "Bimbisara"], "Chandragupta Maurya founded the Maurya Empire around 322 BCE."],
    ["The Battle of Plassey was fought in?", "1757", ["1764", "1857", "1707"], "The Battle of Plassey (1757) established British power in Bengal."],
    ["Who gave the slogan 'Inquilab Zindabad'?", "Bhagat Singh", ["Subhas Chandra Bose", "Lala Lajpat Rai", "Chandrashekhar Azad"], "Bhagat Singh popularised the slogan 'Inquilab Zindabad'."],
    ["The Jallianwala Bagh massacre took place in which year?", "1919", ["1920", "1909", "1915"], "The Jallianwala Bagh massacre occurred on 13 April 1919."],
    ["Who was the founder of the Mughal Empire in India?", "Babur", ["Akbar", "Humayun", "Aurangzeb"], "Babur founded the Mughal Empire after the First Battle of Panipat (1526)."],
    ["The Dandi March (Salt Satyagraha) was led by?", "Mahatma Gandhi", ["Jawaharlal Nehru", "Sardar Patel", "Subhas Chandra Bose"], "Gandhi led the Dandi March in 1930 against the salt tax."],
    ["Who was the first woman ruler of Delhi?", "Razia Sultana", ["Noor Jahan", "Chand Bibi", "Rani Durgavati"], "Razia Sultana was the first and only woman to rule the Delhi Sultanate."],
    ["The Indian National Congress was founded in which year?", "1885", ["1857", "1905", "1920"], "The INC was founded in 1885 by A.O. Hume."],
    ["Who built the Qutub Minar's first storey?", "Qutub-ud-din Aibak", ["Iltutmish", "Akbar", "Shah Jahan"], "Qutub-ud-din Aibak began the Qutub Minar; Iltutmish completed it."],
    ["The ancient university of Nalanda was located in present-day?", "Bihar", ["Uttar Pradesh", "West Bengal", "Odisha"], "Nalanda University was in present-day Bihar."],
    ["Who was the last Mughal emperor?", "Bahadur Shah Zafar", ["Aurangzeb", "Akbar II", "Shah Alam II"], "Bahadur Shah Zafar was the last Mughal emperor, exiled after 1857."],
  ],
  "Geography": [
    ["Which is the longest river in India?", "Ganga", ["Brahmaputra", "Godavari", "Yamuna"], "The Ganga is the longest river flowing within India (~2,525 km)."],
    ["Which is the highest mountain peak in India?", "Kanchenjunga", ["Mount Everest", "Nanda Devi", "K2"], "Kanchenjunga is the highest peak located within India."],
    ["The Tropic of Cancer passes through how many Indian states?", "8", ["6", "7", "9"], "The Tropic of Cancer passes through 8 Indian states."],
    ["Which state has the longest coastline in India?", "Gujarat", ["Tamil Nadu", "Andhra Pradesh", "Maharashtra"], "Gujarat has the longest coastline among Indian states."],
    ["The Sundarbans delta is formed by which rivers?", "Ganga and Brahmaputra", ["Krishna and Godavari", "Narmada and Tapi", "Indus and Sutlej"], "The Sundarbans is formed by the Ganga-Brahmaputra-Meghna delta."],
    ["Which is the largest state of India by area?", "Rajasthan", ["Madhya Pradesh", "Maharashtra", "Uttar Pradesh"], "Rajasthan is the largest Indian state by area."],
    ["The Deccan Plateau is mainly composed of which rock?", "Basalt", ["Granite", "Limestone", "Sandstone"], "The Deccan Plateau is composed mainly of volcanic basalt rock."],
    ["Which river is known as the 'Sorrow of Bihar'?", "Kosi", ["Son", "Gandak", "Ganga"], "The Kosi river is called the 'Sorrow of Bihar' due to frequent floods."],
    ["Which is the smallest state of India by area?", "Goa", ["Sikkim", "Tripura", "Nagaland"], "Goa is the smallest Indian state by area."],
    ["The Palk Strait separates India from?", "Sri Lanka", ["Maldives", "Myanmar", "Bangladesh"], "The Palk Strait lies between India and Sri Lanka."],
    ["Which line divides India and Pakistan?", "Radcliffe Line", ["Durand Line", "McMahon Line", "LoC"], "The Radcliffe Line is the boundary between India and Pakistan."],
    ["The highest waterfall in India is?", "Kunchikal Falls", ["Jog Falls", "Dudhsagar Falls", "Nohkalikai Falls"], "Kunchikal Falls in Karnataka is the highest waterfall in India."],
    ["Which is the largest freshwater lake in India?", "Wular Lake", ["Dal Lake", "Chilika Lake", "Loktak Lake"], "Wular Lake in J&K is the largest freshwater lake in India."],
  ],
  "Economy": [
    ["Who controls the monetary policy in India?", "Reserve Bank of India", ["SEBI", "Ministry of Finance", "NITI Aayog"], "The RBI is responsible for India's monetary policy."],
    ["What does GDP stand for?", "Gross Domestic Product", ["Gross Detailed Product", "General Domestic Profit", "Gross Domestic Profit"], "GDP = Gross Domestic Product."],
    ["NITI Aayog replaced which body?", "Planning Commission", ["Finance Commission", "Election Commission", "RBI"], "NITI Aayog replaced the Planning Commission in 2015."],
    ["Which tax is an example of an indirect tax?", "GST", ["Income Tax", "Corporate Tax", "Wealth Tax"], "GST (Goods and Services Tax) is an indirect tax."],
    ["The Repo rate is decided by?", "RBI", ["SEBI", "Government", "Banks"], "The Repo rate is set by the RBI's Monetary Policy Committee."],
    ["Which regulatory body governs the securities market in India?", "SEBI", ["RBI", "IRDAI", "PFRDA"], "SEBI (Securities and Exchange Board of India) regulates the stock market."],
    ["The first bank to be established in India was?", "Bank of Hindustan", ["State Bank of India", "Reserve Bank of India", "Punjab National Bank"], "The Bank of Hindustan (1770) was the earliest bank in India."],
    ["GST was implemented in India on which date?", "1 July 2017", ["15 August 2016", "26 January 2018", "1 April 2017"], "GST came into effect on 1 July 2017."],
    ["What does 'CRR' stand for?", "Cash Reserve Ratio", ["Credit Reserve Rate", "Cash Repo Rate", "Central Reserve Ratio"], "CRR is the Cash Reserve Ratio banks must keep with the RBI."],
    ["The 'fiscal deficit' is the difference between?", "Total expenditure and total receipts excluding borrowings", ["Imports and exports", "Income and savings", "Revenue and capital"], "Fiscal deficit = total expenditure − total receipts (excluding borrowings)."],
    ["Which is the apex bank for agriculture and rural development in India?", "NABARD", ["RBI", "SIDBI", "EXIM Bank"], "NABARD is the apex development bank for agriculture and rural areas."],
    ["The term 'Blue Chip' is associated with?", "Stock market", ["Agriculture", "Mining", "Defence"], "'Blue chip' refers to shares of well-established, financially sound companies."],
  ],
  "General Science": [
    ["What is the chemical symbol of Gold?", "Au", ["Ag", "Gd", "Go"], "Gold's symbol 'Au' comes from Latin 'Aurum'."],
    ["Which gas is most abundant in Earth's atmosphere?", "Nitrogen", ["Oxygen", "Carbon dioxide", "Hydrogen"], "Nitrogen makes up about 78% of the atmosphere."],
    ["What is the powerhouse of the cell?", "Mitochondria", ["Nucleus", "Ribosome", "Chloroplast"], "Mitochondria produce energy (ATP), hence the 'powerhouse'."],
    ["The unit of electric current is?", "Ampere", ["Volt", "Watt", "Ohm"], "Electric current is measured in Amperes."],
    ["Which vitamin is produced when skin is exposed to sunlight?", "Vitamin D", ["Vitamin A", "Vitamin C", "Vitamin K"], "Sunlight helps the skin synthesize Vitamin D."],
    ["What is the speed of light in vacuum (approx)?", "3 × 10⁸ m/s", ["3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁵ m/s"], "Light travels at about 3 × 10⁸ metres per second in vacuum."],
    ["The chemical symbol for Sodium is?", "Na", ["So", "Sd", "Sm"], "Sodium's symbol 'Na' comes from Latin 'Natrium'."],
    ["Which is the hardest natural substance?", "Diamond", ["Gold", "Iron", "Quartz"], "Diamond is the hardest known natural substance."],
    ["The human body has how many bones in adulthood?", "206", ["201", "210", "300"], "An adult human has 206 bones (newborns have around 300)."],
    ["Which acid is found in the human stomach?", "Hydrochloric acid", ["Sulphuric acid", "Nitric acid", "Acetic acid"], "The stomach secretes hydrochloric acid (HCl) for digestion."],
    ["What is the SI unit of force?", "Newton", ["Joule", "Pascal", "Watt"], "Force is measured in Newtons (N)."],
    ["Which gas is used in electric bulbs (incandescent)?", "Argon", ["Oxygen", "Hydrogen", "Helium"], "Argon (an inert gas) is filled in incandescent bulbs to prevent oxidation."],
    ["The process by which plants make food is called?", "Photosynthesis", ["Respiration", "Transpiration", "Digestion"], "Photosynthesis converts sunlight, CO₂ and water into glucose."],
    ["The 'Universal Donor' blood group is?", "O negative", ["AB positive", "A positive", "B negative"], "O-negative blood is the universal donor type."],
  ],
  "Static GK": [
    ["The headquarters of UNESCO is located in?", "Paris", ["New York", "Geneva", "Rome"], "UNESCO is headquartered in Paris, France."],
    ["Which is the national aquatic animal of India?", "Gangetic Dolphin", ["Blue Whale", "Crocodile", "Turtle"], "The Gangetic Dolphin is India's national aquatic animal."],
    ["Who wrote the national anthem of India?", "Rabindranath Tagore", ["Bankim Chandra", "Sarojini Naidu", "Mahatma Gandhi"], "Rabindranath Tagore wrote 'Jana Gana Mana'."],
    ["The 'Dandiya' folk dance belongs to which state?", "Gujarat", ["Punjab", "Rajasthan", "Kerala"], "Dandiya is a folk dance of Gujarat."],
    ["Which day is celebrated as World Environment Day?", "5 June", ["22 April", "1 May", "8 March"], "World Environment Day is observed on 5 June."],
    ["The currency of Japan is?", "Yen", ["Won", "Yuan", "Ringgit"], "The Japanese currency is the Yen."],
    ["Which is the largest planet in the solar system?", "Jupiter", ["Saturn", "Earth", "Neptune"], "Jupiter is the largest planet in our solar system."],
    ["The headquarters of the United Nations is in?", "New York", ["Geneva", "Paris", "Vienna"], "The UN headquarters is in New York City, USA."],
    ["Which is the national bird of India?", "Peacock", ["Parrot", "Eagle", "Sparrow"], "The Indian Peacock is the national bird of India."],
    ["The 'Bihu' festival is celebrated in which state?", "Assam", ["Bihar", "Odisha", "Manipur"], "Bihu is the main festival of Assam."],
    ["Who was the first Indian to win a Nobel Prize?", "Rabindranath Tagore", ["C.V. Raman", "Mother Teresa", "Amartya Sen"], "Tagore won the Nobel Prize for Literature in 1913."],
    ["The Statue of Unity is a statue of?", "Sardar Vallabhbhai Patel", ["Mahatma Gandhi", "B.R. Ambedkar", "Jawaharlal Nehru"], "The Statue of Unity in Gujarat depicts Sardar Patel."],
    ["Which vitamin deficiency causes scurvy?", "Vitamin C", ["Vitamin A", "Vitamin D", "Vitamin B12"], "Scurvy is caused by a deficiency of Vitamin C."],
    ["The 'Konark Sun Temple' is located in?", "Odisha", ["Tamil Nadu", "Karnataka", "Gujarat"], "The Konark Sun Temple is in Odisha."],
  ],
};

export const GA_TOPICS = Object.keys(POOLS);
export function genGA(topic, rng) {
  const [q, ans, dist, exp] = pick(rng, POOLS[topic]);
  const { options, answerIndex } = buildOptions(rng, ans, dist);
  return { question: q, options, answerIndex, explanation: exp, topic };
}
